### ISSUE TITLE
shark vs linx

### ISSUE THREAD

**Issue by Carolina710** [jimconner/sharkbus#4]
Hi Jim, I'm curious to know if you have any information about the latest protocol for Invacare wheelchairs with Linx electronics. Do you know if it's comparable to the Shark protocol, and if there are any notable differences?
Thanks a lot!

**Comment by jimconner** [comment]
Hi @Carolina710 - I'm afraid I only know about the SharkBus protocol - The spec document was sent to me by the founder of the company many years ago - He's long since retired I'm afraid so I can't ask him about anything newer.
